### PR TITLE
append tr architecture

### LINKED ISSUE #18: paste doesn't work with marks
Tested with v0.0.13-alpha.3, but bug may have existed before then.

CleanShot 2024-08-14 at 00 09 08

I tried debugging this myself but it seems to be a problem inside of `updateSpans`: left is the newSpans, right is the field after update is called. They should be equal.

CleanShot 2024-08-14 at 00 11 28@2x

https://github.com/automerge/automerge-prosemirror/blob/08612db748290d371ae053a7b5831309cd2d65c6/src/pmToAm.ts#L124

### LINKED ISSUE #19: provide a way to add metadata to transaction made from remote changes
Currently, `reconcilePatch` accepts the incoming patches from Automerge and the current `EditorState` from Prosemirror and returns a new `EditorState` to set. For the case of working with the Prosemirror history plugin, it would be nice to be able to mark the transaction created by the incoming patch with [`tx.setMeta('addToHistory', false)`](https://prosemirror.net/docs/ref/#history) so that only changes made locally are added to the history stack.

### PR DESCRIPTION
**Pull request by BrianHung**
Following up the discussion from here https://github.com/automerge/automerge-prosemirror/issues/18#issuecomment-2289998369

Moving off of `intercept` and to `appendTr` is a must-do, as the current behavior breaks any ProseMirror plugins that use `setMeta` (e.g. `history`). `setMeta` is how plugins/components can communicate with other plugins so it's an important functionality. As an example, see how many times [prosemirror uses it in its source code](https://github.com/search?q=org%3AProseMirror%20setMeta&type=code).

Transactions are [not serializable](https://github.com/ProseMirror/prosemirror/issues/890), so previously we were discarding all the metadata by only syncing steps / document changes only in `intercept`.

This PR also replaces `AutoMirror` with an easier `syncPlugin` that is tied to the ProseMirror life-cycle. `onPatch` is initiated and cleaned up automatically now.

fixes #18 
fixes #19

### CODE REVIEW

**Comment by BrianHung** [comment]
@alexjg ready for a first glance

File: src/syncPlugin.ts [hunk 1]
```diff
@@ -0,0 +1,124 @@
...
+import { DocHandle, DocHandleChangePayload } from "@automerge/automerge-repo"
+import pmToAm from "./pmToAm"
+import amToPm from "./amToPm"
+import { docFromSpans } from "./traversal"
+import { patchesToTr } from "./patchesToTr"
+import { ChangeSet } from "prosemirror-changeset"
+import { SchemaAdapter } from "./schema"
+import { isArrayEqual } from "./utils"
+
+export const syncPluginKey = new PluginKey("automerge-sync")
```
Comment (alexjg) [inline src/syncPlugin.ts:12]: Is this a sufficiently unique name? I can see people using this name as a plugin key whilst testing things and then getting very confused.

File: src/syncPlugin.ts [hunk 2]
```diff
@@ -0,0 +1,124 @@
...
+          tr.docs[0],
+          tr.mapping.maps,
+          undefined,
+        )
+      }
+
+      const diff = pmChangeSet.changedRange(amChangeSet)
+      if (!diff || diff.from === diff.to) return undefined
+
+      // Replace the diff range in ProseMirror doc from the AutoMerge doc.
```
Comment (alexjg) [inline src/syncPlugin.ts:105]: Should we log a warning at this point? If the automerge changeset doesn't match the prosemirror changeset then that means we have implemented the `amToPm` part incorrectly right?

**Review by alexjg — COMMENTED** [review]
First off, this is a great patch that implements something I really wanted and didn't have time for, thank you!

I've left a few comments and questions on specific parts of the code. A few more here:

First, the documentation in `README.md` refers to the now missing `AutoMirror`, we should update it to only talk about the `syncPlugin`. I also think we should export `docFromSpans` as `initializeProsemirrorDoc` or similar; IMO `docFromSpans` is a confusing name for users of the library because `doc` can be either a ProseMirror document or an Automerge document.

Secondly, I think we should add a cypress test which exercises this new functionality by entering some text and then undoing it with `ctrl-z`.

File: src/syncPlugin.ts (hunk 1 above)
Comment (BrianHung) [reply src/syncPlugin.ts:12]: The name for a plugin key doesn't have to be unique; [ProseMirror will make one for you](https://github.com/ProseMirror/prosemirror-state/blob/09ffa0c8b5a331f6fbec2809b5bd454e4a43744d/src/plugin.ts#L134). With plugin keys, the only way to access them and their plugin state would then be by importing the plugin key itself, and using it directly.

For example, `tr.getMeta(syncPluginKey)`. It is true if you use strings directly, e.g. `tr.getMeta('sync')`, those should unique to not conflict with other plugins.

File: src/syncPlugin.ts (hunk 2 above)
Comment (BrianHung) [reply src/syncPlugin.ts:105]: Think it could be either `pmToAm` or `amToPm` is mismatched, yeah. `console.warn` with mismatched states and the incoming transactions with a link to this repo to file an issue would be good.

File: src/index.ts [hunk 3]
```diff
@@ -9,3 +8,4 @@ export {
 } from "./schema"
 export { basicSchemaAdapter } from "./basicSchema"
 export { docFromSpans, blocksFromNode } from "./traversal"
```
Comment (alexjg) [inline src/index.ts:10]: I think the only thing remaining to do is rename the `docFromSpans` export to `initializeProsemirrorDoc`.

Comment (BrianHung) [reply src/index.ts:10]: What about `pmDocFromSpans`? Subsequently, also rename `blocksFromNode` to `pmNodeToSpans`?

**Comment by alexjg** [comment]
Nice work @BrianHung, much appreciated. I'll try and get a release out today.
